// react/src/starWars/PeopleList.tsx
import React from "react";
import { useState } from "react";
import { People, fetchPeoples } from "../domain/people";
import { PeopleCard } from "./PeopleCard";
import { useEffect } from "react";

export function PeopleList() {
  const [peopleList, setPeopleList] = useState<People[]>([]);
  const [title, setTitle] = useState("");

  useEffect(() => {
    const fetchPeople = async () => {
      const list = await fetchPeoples();
      setPeopleList(list);
    };

    fetchPeople();
  }, []);

  const handlePeopleSelect = (value: string) => {
    setTitle(value);
  };

  return (
    <div>
      <h2>{title}</h2>
      {peopleList &&
        peopleList.map((people, index) => (
          <PeopleCard
            key={index}
            peopleProps={people}
            onPeopleSelect={handlePeopleSelect}
          />
        ))}
    </div>
  );
}

// vue/src/components/PeopleList.vue
<script setup lang="ts">
import { ref } from 'vue';
import PeopleCard from './PeopleCard.vue'
import { People, fetchPeoples } from '../domain/people'

const list = ref<People[]>([])
const title = ref("")

fetchPeoples().then(people => list.value = people)

const handlePeopleClick = (event: string) => title.value = event

</script>

<template>
    <h3>{{ title }}</h3>
    <PeopleCard v-for="people in list" :people="people" v-on:on-people-click="handlePeopleClick"></PeopleCard>
</template>
